name: Bus API CI

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t bus-api -f Dockerfile .
      - name: Tags
        run: |
          docker tag bus-api ${{ secrets.DOCKER_USER }}/bus-api:${{ github.sha }}
          docker tag bus-api ${{ secrets.DOCKER_USER }}/bus-api:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/bus-api:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/bus-api:latest
